/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    services: Service;
    testimonials: Testimonial;
    customers: Customer;
    bookings: Booking;
    'partner-applications': PartnerApplication;
    'partner-kyc-submissions': PartnerKycSubmission;
    providers: Provider;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'partner-applications': PartnerApplicationsSelect<false> | PartnerApplicationsSelect<true>;
    'partner-kyc-submissions': PartnerKycSubmissionsSelect<false> | PartnerKycSubmissionsSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'site-pages': SitePage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-pages': SitePagesSelect<false> | SitePagesSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  /**
   * Short code such as AC, PL, EL, CL, PT, CCTV.
   */
  icon?: string | null;
  description: string;
  featured?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  slug?: string | null;
  category: number | Category;
  /**
   * Optional short code. Leave blank to auto-pick by service name.
   */
  icon?: string | null;
  /**
   * Optional service logo/image shown on website cards. Falls back to the icon if empty.
   */
  logo?: (number | null) | Media;
  /**
   * Optional wide photo shown on this service detail page hero.
   */
  heroImage?: (number | null) | Media;
  description: string;
  basePrice: number;
  durationMinutes: number;
  includes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  available?: boolean | null;
  /**
   * Show this service in popular service sections.
   */
  popular?: boolean | null;
  /**
   * Lower numbers appear first on the website.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  city: string;
  rating: number;
  quote: string;
  service?: string | null;
  photo?: (number | null) | Media;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  customer: number | Customer;
  service: number | Service;
  serviceName: string;
  estimatedPrice: number;
  scheduledDate: string;
  timeSlot: '09:00' | '10:00' | '14:00' | '17:00';
  phone: string;
  address: string;
  /**
   * Optional GPS latitude shared from the booking form.
   */
  locationLatitude?: number | null;
  /**
   * Optional GPS longitude shared from the booking form.
   */
  locationLongitude?: number | null;
  /**
   * Open this link to view the customer location on Google Maps.
   */
  locationMapLink?: string | null;
  status: 'pending' | 'confirmed' | 'in-progress' | 'completed' | 'cancelled';
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-applications".
 */
export interface PartnerApplication {
  id: number;
  applicantName: string;
  businessName?: string | null;
  phone: string;
  email: string;
  serviceArea: string;
  experienceYears?: number | null;
  services: (number | Service)[];
  availability?:
    | {
        option: string;
        id?: string | null;
      }[]
    | null;
  message?: string | null;
  status: 'new' | 'contacted' | 'approved' | 'rejected';
  kycStatus: 'pending' | 'submitted' | 'verified' | 'rejected';
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-kyc-submissions".
 */
export interface PartnerKycSubmission {
  id: number;
  partnerApplication: number | PartnerApplication;
  govtIdNumber: string;
  govtIdFile: number | Media;
  bankAccountName: string;
  bankName: string;
  accountNumber: string;
  ifscCode: string;
  partnerPhoto: number | Media;
  status: 'submitted' | 'under-review' | 'verified' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  providerName: string;
  phone: string;
  email?: string | null;
  serviceArea: string;
  services: (number | Service)[];
  status: 'active' | 'paused' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'partner-applications';
        value: number | PartnerApplication;
      } | null)
    | ({
        relationTo: 'partner-kyc-submissions';
        value: number | PartnerKycSubmission;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  description?: T;
  featured?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  icon?: T;
  logo?: T;
  heroImage?: T;
  description?: T;
  basePrice?: T;
  durationMinutes?: T;
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  available?: T;
  popular?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  rating?: T;
  quote?: T;
  service?: T;
  photo?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  customer?: T;
  service?: T;
  serviceName?: T;
  estimatedPrice?: T;
  scheduledDate?: T;
  timeSlot?: T;
  phone?: T;
  address?: T;
  locationLatitude?: T;
  locationLongitude?: T;
  locationMapLink?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-applications_select".
 */
export interface PartnerApplicationsSelect<T extends boolean = true> {
  applicantName?: T;
  businessName?: T;
  phone?: T;
  email?: T;
  serviceArea?: T;
  experienceYears?: T;
  services?: T;
  availability?:
    | T
    | {
        option?: T;
        id?: T;
      };
  message?: T;
  status?: T;
  kycStatus?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-kyc-submissions_select".
 */
export interface PartnerKycSubmissionsSelect<T extends boolean = true> {
  partnerApplication?: T;
  govtIdNumber?: T;
  govtIdFile?: T;
  bankAccountName?: T;
  bankName?: T;
  accountNumber?: T;
  ifscCode?: T;
  partnerPhoto?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  providerName?: T;
  phone?: T;
  email?: T;
  serviceArea?: T;
  services?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroEyebrow: string;
  heroTitle: string;
  heroCopy: string;
  heroImage?: (number | null) | Media;
  primaryActionLabel: string;
  primaryActionHref: string;
  secondaryActionLabel: string;
  secondaryActionHref: string;
  categoryHighlightsLimit: number;
  popularEyebrow: string;
  popularTitle: string;
  popularLimit: number;
  workflowEyebrow: string;
  workflowTitle: string;
  workflowCopy: string;
  processSteps?:
    | {
        number: string;
        title: string;
        copy: string;
        id?: string | null;
      }[]
    | null;
  pipelineStatuses?:
    | {
        label: string;
        detail: string;
        color: 'gold' | 'teal' | 'coral' | 'green';
        id?: string | null;
      }[]
    | null;
  pricingEyebrow: string;
  pricingTitle: string;
  pricingLimit: number;
  customerTrustEyebrow: string;
  customerTrustTitle: string;
  customerTrustLimit: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages".
 */
export interface SitePage {
  id: number;
  servicesEyebrow: string;
  servicesTitle: string;
  servicesCopy?: string | null;
  servicesHeroImage?: (number | null) | Media;
  aboutEyebrow: string;
  aboutTitle: string;
  aboutCopy: string;
  aboutHeroImage?: (number | null) | Media;
  aboutBody?:
    | {
        copy: string;
        id?: string | null;
      }[]
    | null;
  aboutProcessSteps?:
    | {
        number: string;
        title: string;
        copy: string;
        id?: string | null;
      }[]
    | null;
  contactEyebrow: string;
  contactTitle: string;
  contactCopy: string;
  contactCards?:
    | {
        title: string;
        body: string;
        actionLabel?: string | null;
        actionHref?: string | null;
        id?: string | null;
      }[]
    | null;
  bookingEyebrow: string;
  bookingTitle: string;
  bookingCopy: string;
  bookingPanelKicker: string;
  bookingPanelTitle: string;
  bookingButtonLabel: string;
  bookingPanelNote: string;
  bookingNextTitle: string;
  bookingProcessSteps?:
    | {
        number: string;
        title: string;
        copy: string;
        id?: string | null;
      }[]
    | null;
  partnerEyebrow: string;
  partnerTitle: string;
  partnerCopy: string;
  partnerHeroImage?: (number | null) | Media;
  partnerPanelKicker: string;
  partnerPanelTitle: string;
  partnerMissingFieldsMessage: string;
  partnerAvailabilityOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  partnerNotesPlaceholder: string;
  partnerSubmitLabel: string;
  partnerPanelNote: string;
  partnerReviewEyebrow: string;
  partnerReviewTitle: string;
  partnerReviewCopy: string;
  partnerReviewStatuses?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  kycEyebrow: string;
  kycTitle: string;
  kycCopy: string;
  kycSubmittedEyebrow: string;
  kycSubmittedTitle: string;
  kycSubmittedCopy: string;
  kycApplicationEyebrow: string;
  kycApplicationTitle: string;
  kycApplicationCopy: string;
  kycContinueLabel: string;
  kycLaterLabel: string;
  kycFormKicker: string;
  kycMissingFieldsMessage: string;
  kycSubmitLabel: string;
  kycFormNote: string;
  kycApplicationNeededEyebrow: string;
  kycApplicationNeededTitle: string;
  kycApplicationNeededCopy: string;
  kycApplicationErrorMessage: string;
  kycPartnerFormLabel: string;
  kycAdminEyebrow: string;
  kycAdminTitle: string;
  kycAdminCopy: string;
  kycAdminStatuses?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  brandInitial: string;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  primaryActionLabel: string;
  primaryActionHref: string;
  secondaryActionLabel: string;
  secondaryActionHref: string;
  footerCopy: string;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroCopy?: T;
  heroImage?: T;
  primaryActionLabel?: T;
  primaryActionHref?: T;
  secondaryActionLabel?: T;
  secondaryActionHref?: T;
  categoryHighlightsLimit?: T;
  popularEyebrow?: T;
  popularTitle?: T;
  popularLimit?: T;
  workflowEyebrow?: T;
  workflowTitle?: T;
  workflowCopy?: T;
  processSteps?:
    | T
    | {
        number?: T;
        title?: T;
        copy?: T;
        id?: T;
      };
  pipelineStatuses?:
    | T
    | {
        label?: T;
        detail?: T;
        color?: T;
        id?: T;
      };
  pricingEyebrow?: T;
  pricingTitle?: T;
  pricingLimit?: T;
  customerTrustEyebrow?: T;
  customerTrustTitle?: T;
  customerTrustLimit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages_select".
 */
export interface SitePagesSelect<T extends boolean = true> {
  servicesEyebrow?: T;
  servicesTitle?: T;
  servicesCopy?: T;
  servicesHeroImage?: T;
  aboutEyebrow?: T;
  aboutTitle?: T;
  aboutCopy?: T;
  aboutHeroImage?: T;
  aboutBody?:
    | T
    | {
        copy?: T;
        id?: T;
      };
  aboutProcessSteps?:
    | T
    | {
        number?: T;
        title?: T;
        copy?: T;
        id?: T;
      };
  contactEyebrow?: T;
  contactTitle?: T;
  contactCopy?: T;
  contactCards?:
    | T
    | {
        title?: T;
        body?: T;
        actionLabel?: T;
        actionHref?: T;
        id?: T;
      };
  bookingEyebrow?: T;
  bookingTitle?: T;
  bookingCopy?: T;
  bookingPanelKicker?: T;
  bookingPanelTitle?: T;
  bookingButtonLabel?: T;
  bookingPanelNote?: T;
  bookingNextTitle?: T;
  bookingProcessSteps?:
    | T
    | {
        number?: T;
        title?: T;
        copy?: T;
        id?: T;
      };
  partnerEyebrow?: T;
  partnerTitle?: T;
  partnerCopy?: T;
  partnerHeroImage?: T;
  partnerPanelKicker?: T;
  partnerPanelTitle?: T;
  partnerMissingFieldsMessage?: T;
  partnerAvailabilityOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  partnerNotesPlaceholder?: T;
  partnerSubmitLabel?: T;
  partnerPanelNote?: T;
  partnerReviewEyebrow?: T;
  partnerReviewTitle?: T;
  partnerReviewCopy?: T;
  partnerReviewStatuses?:
    | T
    | {
        label?: T;
        id?: T;
      };
  kycEyebrow?: T;
  kycTitle?: T;
  kycCopy?: T;
  kycSubmittedEyebrow?: T;
  kycSubmittedTitle?: T;
  kycSubmittedCopy?: T;
  kycApplicationEyebrow?: T;
  kycApplicationTitle?: T;
  kycApplicationCopy?: T;
  kycContinueLabel?: T;
  kycLaterLabel?: T;
  kycFormKicker?: T;
  kycMissingFieldsMessage?: T;
  kycSubmitLabel?: T;
  kycFormNote?: T;
  kycApplicationNeededEyebrow?: T;
  kycApplicationNeededTitle?: T;
  kycApplicationNeededCopy?: T;
  kycApplicationErrorMessage?: T;
  kycPartnerFormLabel?: T;
  kycAdminEyebrow?: T;
  kycAdminTitle?: T;
  kycAdminCopy?: T;
  kycAdminStatuses?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandInitial?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  primaryActionLabel?: T;
  primaryActionHref?: T;
  secondaryActionLabel?: T;
  secondaryActionHref?: T;
  footerCopy?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}